name: CI
on: push
jobs:
  lint_ptos_fetcher:
    name: 'Lint PTOs fetcher'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/ptos_fetcher
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint:all
